### ISSUE TITLE
terminal_minecraft.c:7:10: fatal error: X11/Xlib.h: No such file or directory

### ISSUE THREAD

**Issue by Jeremy5909** [Kameldieb/ascii_minecraft#4] opened 2021-10-31 23:35 UTC

**Comment by georgewoodall82** [comment] 2021-11-01 07:34
`sudo apt-get install libx11-dev`

**Comment by georgewoodall82** [comment] 2021-11-01 07:36
Also a duplicate of #3

**Closed as completed** 2023-06-19 11:13 UTC
